[tool.poetry]
name = "portfolio"
version = "0.1.0"
description = ""
authors = ["truthless-dev <truthless.deviant248@simplelogin.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
