[project]
name = "portfolio"
version = "0.2.0"
description = "Personal portfolio website"
readme = "README.md"
license = "MIT"
authors = [
    { name = "truthless-dev", email = "truthless.deviant248@simplelogin.fr" },
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "django>=5.1.0,<6",
    "gunicorn>=23.0.0,<24",
    "psycopg2-binary>=2.9.9,<3",
    "python-dotenv>=1.0.1,<2",
    "django-recaptcha>=4.0.0,<5",
    "ruff>=0.15.11,<1",
]

[dependency-groups]
dev = [
    "pre-commit>=3.8.0,<4",
    "ruff>=0.15.11,<1",
]
